#include "stm32f767xx.h"

void init_all()
{
	RCC->PLLCFGR |= RCC_PLLCFGR_PLLM_4 | RCC_PLLCFGR_PLLN_7 | RCC_PLLCFGR_PLLN_6 | RCC_PLLCFGR_PLLSRC;
	RCC->CFGR |= RCC_CFGR_PPRE1_2 | RCC_CFGR_PPRE2_2;
	FLASH->ACR |= FLASH_ACR_LATENCY_2WS;
	RCC->CR |= RCC_CR_HSEON;
	while((RCC->CR & RCC_CR_HSERDY) == 0);
	RCC->CR |= RCC_CR_PLLON;
	while((RCC->CR & RCC_CR_PLLRDY) == 0);
	RCC->CFGR |= RCC_CFGR_SW_1;
	while((RCC->CFGR & RCC_CFGR_SWS_Msk) != RCC_CFGR_SWS_1);
	RCC->CR &= ~RCC_CR_HSION;

	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOBEN;
	RCC->APB1ENR |= RCC_APB1ENR_TIM4EN;
	RCC->APB2ENR |= RCC_APB2ENR_SYSCFGEN;
	GPIOB->MODER |= GPIO_MODER_MODER8_1;
	GPIOB->AFR[1] |= GPIO_AFRH_AFRH0_1;
	TIM4->ARR = 100;
	TIM4->CCR3 = 50;
	TIM4->CCMR2 |= TIM_CCMR2_OC3M_1 | TIM_CCMR2_OC3M_2;
	TIM4->CCER |= TIM_CCER_CC3E;
	TIM4->CR1 |= TIM_CR1_CEN;
	GPIOB->MODER |= GPIO_MODER_MODER7_0;
}

int main(void)
{
	init_all();
	while(1);
}
